version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -s . -p "test_*.py" -v

workflows:
  build_and_test:
    jobs:
      - test
